### PR TITLE
feat: user profile command

### PR DESCRIPTION
**Pull request by cheeze2000**

### CODE REVIEW

**Review by itsUrcute — COMMENTED** [review]
are the [question numbers](https://github.com/binarysus/algo-chan/pull/6/files#diff-4e8ccd6121c0cef931b8a966c3f16da67b3b1bc411fb8974ae35130419644432) truly constant?
from what i understand can't new questions be added?

**Comment by cheeze2000** [comment]
> are the [question numbers](https://github.com/binarysus/algo-chan/pull/6/files#diff-4e8ccd6121c0cef931b8a966c3f16da67b3b1bc411fb8974ae35130419644432) truly constant?
> from what i understand can't new questions be added?

they represent the max number of questions per difficulty which for some reason isn't available in the API. it can be treated as constants for now since it's not something that changes regularly

**Comment by TogarashiPepper** [comment]
any specific reason message.channel.send is being used over message.reply?

**Review by 1mmunity — CHANGES_REQUESTED** [review]
```json
{
  "BINARYSEARCH_API": "https://binarysearch.com/api/users/USERNAME/profile"
}
```
might want to categorize these, and for readability use {USERNAME} to indicate dynamic input.

```json
{
  "BINARYSEARCH_API": {
    "profile": "https://binarysearch.com/api/users/{USERNAME}/profile"
  }
}
```

**Comment by TogarashiPepper** [comment]
oh wait, since crawl isnt here

this needs a rebase.

**Pull request closed without merging**
